version: '2.4'
services:
  minecraft-server:
    image: itzg/minecraft-server:multiarch
    container_name: ${CONTAINER_NAME}
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
    environment:
      EULA: 'TRUE'
      SEED: DW20LP116SUPERHYPE # this is the seed Direwolf is using in his stream, delete this line if you want a random seed
      VERSION: 1.16.4
      TYPE: 'FTBA'
      FTB_MODPACK_ID: 79
      INIT_MEMORY: 8G
      MAX_MEMORY: 12G
      USE_AIKAR_FLAGS: 'true'
      USE_LARGE_PAGES: 'true'
      # yes I know this is redundant
      # its a reminder to setup your .env file
      WHITELIST: ${WHITELIST} 
      OPS: ${OPS} 
      MOTD: ${MOTD} 
    tty: true
    stdin_open: true
    restart: unless-stopped
